version: '3.7'

services:
  frontend:
    build:
      context: frontend/
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /c/Users/Deven/Work/projects/us_accidents_data_visualization/us_accidents_data_visualization/frontend:/home/node
      - /home/node/node_modules
    ports:
      - 3000:3000