version: '3.7'

services:
  frontend:
    build:
      context: frontend/
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/:/home/node
      - /home/node/node_modules
    ports:
      - 3000:3000